/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaVIEW;

import SistemaCTR.PorcentagemCTR;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author VINICIUS
 */
public class ConfiguracaoVIEW extends javax.swing.JDialog {

    PorcentagemCTR objporcentagemCTR = new PorcentagemCTR();
    ResultSet consulta = null;

    /**
     * Creates new form ConfiguracaoVIEW
     *
     * @param parent
     * @param modal
     */
    public ConfiguracaoVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Configuração de Porcentagem");
        this.setLocationRelativeTo(null);
        txtAcrescimo.setDocument(new SomenteNumeros(2));
        txtDesconto.setDocument(new SomenteNumeros(2));
        ConsultarPorcentagem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAcrescimo = new javax.swing.JTextField();
        txtDesconto = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAtualizacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Acréscimo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 21, 60, 14);

        jLabel2.setText("Desconto:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 50, 60, 14);

        txtAcrescimo.setForeground(new java.awt.Color(0, 0, 204));
        txtAcrescimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAcrescimoKeyPressed(evt);
            }
        });
        getContentPane().add(txtAcrescimo);
        txtAcrescimo.setBounds(70, 20, 40, 20);

        txtDesconto.setForeground(new java.awt.Color(204, 0, 0));
        txtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescontoFocusGained(evt);
            }
        });
        txtDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescontoKeyPressed(evt);
            }
        });
        getContentPane().add(txtDesconto);
        txtDesconto.setBounds(70, 50, 40, 20);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(20, 106, 80, 23);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(110, 106, 80, 23);

        jLabel3.setText("Atualização:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 80, 60, 14);
        getContentPane().add(txtAtualizacao);
        txtAtualizacao.setBounds(70, 80, 70, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("%");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 20, 30, 20);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("%");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 50, 30, 20);

        setBounds(0, 0, 257, 174);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAcrescimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcrescimoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (txtAcrescimo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher o campo acrescimo!", "MENSAGEM", JOptionPane.WARNING_MESSAGE);
                txtAcrescimo.requestFocusInWindow();
            } else {
                txtDesconto.requestFocusInWindow();
            }

        }
    }//GEN-LAST:event_txtAcrescimoKeyPressed

    private void txtDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            Salvar();
        }
    }//GEN-LAST:event_txtDescontoKeyPressed

    private void txtDescontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescontoFocusGained
        txtDesconto.setText("");
    }//GEN-LAST:event_txtDescontoFocusGained

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void Salvar() {
        if (txtDesconto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher o campo desconto!", "MENSAGEM", JOptionPane.WARNING_MESSAGE);
            txtDesconto.requestFocusInWindow();
        } else {
            AtualizarPorcentagem();

        }
    }

    private void AtualizarPorcentagem() {
        try {
            if (objporcentagemCTR.AtualizarPorcentagemCTR(Integer.parseInt(txtAcrescimo.getText()), Integer.parseInt(txtDesconto.getText()))) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!", "MENSAGEM", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar! " + e.getMessage(), "MENSAGEM", JOptionPane.WARNING_MESSAGE);

        }
    }

    private void ConsultarPorcentagem() {
        try {
            consulta = objporcentagemCTR.ConsultarPorcentagemCTR();
            if (consulta.next()) {
                txtAcrescimo.setText(consulta.getString("acrescimo"));
                txtDesconto.setText(consulta.getString("desconto"));
                txtAtualizacao.setText(consulta.getString("resultado"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Consultar Porcentagem " + e.getMessage(), "MENSAGEM", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ConfiguracaoVIEW dialog = new ConfiguracaoVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAcrescimo;
    private javax.swing.JTextField txtAtualizacao;
    private javax.swing.JTextField txtDesconto;
    // End of variables declaration//GEN-END:variables
}
