/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaVIEW;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class PedeSenhaVIEW extends javax.swing.JDialog {

    char[] pegaSenha;
    String senha;

    /**
     * Creates new form PedeSenhaVIEW
     */
    public PedeSenhaVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SENHA");
        UtilVIEW.Icone(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPegaSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Digite a senha:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 14);

        txtPegaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPegaSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtPegaSenha);
        txtPegaSenha.setBounds(10, 30, 180, 20);

        setBounds(0, 0, 215, 103);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPegaSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPegaSenhaKeyPressed

        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                pegaSenha = txtPegaSenha.getPassword();
                senha = String.valueOf(pegaSenha);
                if (senha.equals("1995")) {
                    this.dispose();
                    new ContaCorrenteVIEW(null, true).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Senha não confere!");
                    txtPegaSenha.setText("");
                    txtPegaSenha.requestFocusInWindow();
                }
            }

        } catch (HeadlessException e) {
        }


    }//GEN-LAST:event_txtPegaSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedeSenhaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedeSenhaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedeSenhaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedeSenhaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PedeSenhaVIEW dialog = new PedeSenhaVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtPegaSenha;
    // End of variables declaration//GEN-END:variables
}
