/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaVIEW;

import SistemaCTR.UsuarioCTR;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class UsuarioVIEW extends javax.swing.JDialog {

    char[] pegaSenha;
    String senha;

    /**
     * Creates new form UsuarioVIEW
     *
     * @param parent
     * @param modal
     */
    public UsuarioVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        UtilVIEW.Icone(this);
        this.setLocationRelativeTo(null);
        UtilVIEW.DesabilitarCampos(jPanel1);
        setTitle("CADASTRO DE USUÁRIO");
        ConsultarUsuarioVIEW();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnNovo = new javax.swing.JMenu();
        btnSalvar = new javax.swing.JMenu();
        btnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Código:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 70, 14);

        txtCodigo.setEditable(false);
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(10, 30, 60, 20);

        jLabel2.setText("Login:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 10, 70, 14);
        jPanel1.add(txtLogin);
        txtLogin.setBounds(80, 30, 140, 20);

        jLabel3.setText("Senha:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 10, 34, 14);
        jPanel1.add(txtSenha);
        txtSenha.setBounds(230, 30, 140, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 60);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuários Cadastrados:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código:", "Login:", "Data:", "Hora:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 360, 140);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/relatorio_32x32.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnNovo);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/disquete_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSalvar);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/casa_32x32.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 397, 285);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        pegaSenha = txtSenha.getPassword();
        senha = String.valueOf(pegaSenha);
        if (txtLogin.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher o campo login!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
            txtLogin.requestFocusInWindow();
        } else if (senha.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher o campo senha!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
            txtSenha.requestFocusInWindow();
        } else {
            if (txtCodigo.getText().equals("")) {
                CadastrarUsuarioVIEW();
            } else {
                AlterarUsuarioVIEW();
            }
            ConsultarUsuarioVIEW();
            UtilVIEW.LimparCampos(jPanel1);
            txtLogin.requestFocusInWindow();
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        UtilVIEW.HabilitarCampos(jPanel1);
        txtLogin.requestFocusInWindow();
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        if (evt.getClickCount() == 2) {
            txtCodigo.setText(tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 0).toString());
            txtLogin.setText(tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 1).toString());
            txtLogin.requestFocusInWindow();
            tblUsuario.clearSelection();
        }
    }//GEN-LAST:event_tblUsuarioMouseClicked

    public void CadastrarUsuarioVIEW() {
        try {
            UsuarioCTR objusuarioCTR = new UsuarioCTR();
            if (objusuarioCTR.CadastrarUsuarioCTR(txtLogin.getText(), senha)) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!", "MENSAGEM",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar o usuario!", "ERRO",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void AlterarUsuarioVIEW() {
        try {
            UsuarioCTR objusuarioCTR = new UsuarioCTR();
            if (objusuarioCTR.AlterarUsuarioCTR(txtLogin.getText(),
                    senha, txtCodigo.getText())) {
                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!", "MENSAGEM",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar o usuario!", "ERRO",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void ConsultarUsuarioVIEW() {
        try {
            UsuarioCTR objusuarioCTR = new UsuarioCTR();
            ResultSet rs = null;
            rs = objusuarioCTR.ConsultarLoginCTR();
            RestaurarUsuarioVIEW(rs);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar o usuario!", "ERRO",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void RestaurarUsuarioVIEW(ResultSet rs) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblUsuario.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getString("codigo"), rs.getString("login"),
                    rs.getString("data"), rs.getString("hora")});
            }
            tblUsuario.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao restaurar o usuario!", "ERRO",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UsuarioVIEW dialog = new UsuarioVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnNovo;
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenu btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
