/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaVIEW;


import SistemaCTR.UsuarioCTR;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class LogarVIEW extends javax.swing.JDialog {

    UsuarioCTR objusuarioCTR = new UsuarioCTR();
    ResultSet func = null;
    int cont = 0;
    char[] pegaSenha;
    String senha;

    /**
     * Creates new form LogarVIEW
     *
     * @param parent
     * @param modal
     */
    public LogarVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("LOGAR");
        UtilVIEW.VerificaCapsLock(lblMensagem);
        UtilVIEW.MudarCursor(btnEntrar, btnSair);
        UtilVIEW.Icone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnEntrar = new javax.swing.JMenu();
        btnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Usuário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 70, 14);

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(60, 10, 140, 20);

        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 80, 14);

        lblMensagem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 0, 0));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMensagem);
        lblMensagem.setBounds(48, 68, 140, 20);

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaKeyReleased(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(60, 40, 140, 20);

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pessoas_32x32.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEntrar);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/casa_32x32.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 230, 159);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        UtilVIEW.VerificaCapsLock(lblMensagem);
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void txtSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyReleased
        UtilVIEW.VerificaCapsLock(lblMensagem);
    }//GEN-LAST:event_txtSenhaKeyReleased

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            try {
                if (cont == 3) {
                    System.exit(0);
                } else {
                    pegaSenha = txtSenha.getPassword();
                    senha = String.valueOf(pegaSenha);
                    func = objusuarioCTR.ConsultarUsuarioCTR(txtUsuario.getText(),
                            UtilVIEW.Criptografar(senha));
                    if (func.next()) {
                        if (!func.getString("login").equals(txtUsuario.getText())
                                || !func.getString("senha").equals(UtilVIEW.Criptografar(senha))) {
                            txtUsuario.setText("");
                            txtSenha.setText("");
                            JOptionPane.showMessageDialog(null, "Usuário ou senha não conferem!",
                                    "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                            cont += 1;
                            txtUsuario.requestFocusInWindow();
                        } else {
                            this.dispose();
                            new PrincipalVIEW().setVisible(true);
                        }
                    } else {
                        txtUsuario.setText("");
                        txtSenha.setText("");
                        JOptionPane.showMessageDialog(null, "Usuário ou senha não conferem!",
                                "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                        cont += 1;
                        txtUsuario.requestFocusInWindow();
                    }
                }

            } catch (SQLException | HeadlessException | NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Erro ao Logar",
                        "ERRO", JOptionPane.ERROR_MESSAGE);
                try {
                    int op = -1;
                    op = JOptionPane.showConfirmDialog(null, "Deseja restaurar o banco?",
                            "PERGUNTA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (op == 0) {
                        UtilVIEW.CriarBanco();
                        UtilVIEW.realizaRestore();
                        txtUsuario.setText("");
                        txtSenha.setText("");
                        txtUsuario.requestFocusInWindow();
                    } else if (op == 1) {

                    }
                } catch (IOException | InterruptedException ex) {
                    System.out.println("AQUI " + ex.getMessage());
                }
            }

        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            txtSenha.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        try {
            if (cont == 3) {
                System.exit(0);
            } else {
                pegaSenha = txtSenha.getPassword();
                senha = String.valueOf(pegaSenha);
                func = objusuarioCTR.ConsultarUsuarioCTR(txtUsuario.getText(),
                        UtilVIEW.Criptografar(senha));
                if (func.next()) {
                    if (!func.getString("login").equals(txtUsuario.getText())
                            || !func.getString("senha").equals(UtilVIEW.Criptografar(senha))) {
                        txtUsuario.setText("");
                        txtSenha.setText("");
                        JOptionPane.showMessageDialog(null, "Usuário ou senha não conferem!",
                                "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                        cont += 1;
                        txtUsuario.requestFocusInWindow();
                    } else {
                        this.dispose();
                        new PrincipalVIEW().setVisible(true);
                    }
                } else {
                    txtUsuario.setText("");
                    txtSenha.setText("");
                    JOptionPane.showMessageDialog(null, "Usuário ou senha não conferem!",
                            "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    cont += 1;
                    txtUsuario.requestFocusInWindow();
                }
            }

        } catch (SQLException | HeadlessException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Logar",
                    "ERRO", JOptionPane.ERROR_MESSAGE);
            System.out.println(""+e.getMessage());
            txtUsuario.requestFocusInWindow();

            try {
                int op = -1;
                op = JOptionPane.showConfirmDialog(null, "Deseja restaurar o banco?",
                        "PERGUNTA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (op == 0) {
                    UtilVIEW.CriarBanco();
                    UtilVIEW.realizaRestore();
                } else if (op == 1) {

                }
            } catch (IOException | InterruptedException ex) {
                System.out.println("AQUI " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogarVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogarVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogarVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogarVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                LogarVIEW dialog = new LogarVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnEntrar;
    private javax.swing.JMenu btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMensagem;
    public static javax.swing.JPasswordField txtSenha;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
