/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaVIEW;

import SistemaDAO.ConectaBanco;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import javax.mail.MessagingException;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Vinicius
 */
public class PrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVIEW
     */
    public PrincipalVIEW() {
        try {
            this.setContentPane(new MarcaDagua("/SolucaoSistemas/src/Imagem/Irineu.PNG"));

        } catch (IOException ex) {
            System.out.println("Imagem não encontrada!");
        }
        initComponents();
        this.setExtendedState(PrincipalVIEW.MAXIMIZED_BOTH);
        this.setIconImage(
                Toolkit.getDefaultToolkit().
                getImage("/SolucaoSistemas/src/Imagem/cifrao_32x32.png"));
        setTitle("ESCRITÓRIO RURAL");
        btnArquivo.setMnemonic(KeyEvent.VK_1);
        btnCadastro.setMnemonic(KeyEvent.VK_2);
        btnCaixa.setMnemonic(KeyEvent.VK_3);
        btnRelatorios.setMnemonic(KeyEvent.VK_4);
        mnuUtilitarios.setMnemonic(KeyEvent.VK_5);
        btnSobre.setMnemonic(KeyEvent.VK_6);
        btnSair.setMnemonic(KeyEvent.VK_7);
        RegistarAtalhos();
    }

     private void RegistarAtalhos() {
        JPanel painel = (JPanel) getContentPane();
        //Criamos as ações
        ActionMap mapear = painel.getActionMap();
        mapear.put("Arquivo", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnArquivo.doClick(1);
            }
        });
        mapear.put("Cadastro", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnCadastro.doClick();
            }
        });
        mapear.put("Conta", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnCaixa.doClick();
            }
        });

        mapear.put("Relatorio", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnRelatorios.doClick();
            }
        });

        mapear.put("Sobre", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnSobre.doClick();

            }
        });
        mapear.put("Sair", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnSair.doClick();

            }
        });
        mapear.put("Utilitarios", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mnuUtilitarios.doClick();

            }
        });
         mapear.put("Sair", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnSair.doClick();

            }
        });

        //Registramos os componentes que queremos para as ações
        InputMap imap = painel.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW);
        imap.put(KeyStroke.getKeyStroke("F4"), "Conta");
        imap.put(KeyStroke.getKeyStroke("F3"), "Cadastro");
        imap.put(KeyStroke.getKeyStroke("F2"), "Arquivo");
        imap.put(KeyStroke.getKeyStroke("F5"), "Relatorio");
        imap.put(KeyStroke.getKeyStroke("F7"), "Sobre");
        imap.put(KeyStroke.getKeyStroke("F8"), "Sair");
        imap.put(KeyStroke.getKeyStroke("F6"), "Utilitarios");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnArquivo = new javax.swing.JMenu();
        mnuBackup = new javax.swing.JMenuItem();
        btnCadastro = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenuItem();
        mnuPorcentagem = new javax.swing.JMenuItem();
        btnCaixa = new javax.swing.JMenu();
        btnRelatorios = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        mnuUtilitarios = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        btnSobre = new javax.swing.JMenu();
        btnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        btnArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/arquivo_32x32.png"))); // NOI18N
        btnArquivo.setText("F2-Arquivo");

        mnuBackup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        mnuBackup.setText("Backup");
        mnuBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBackupActionPerformed(evt);
            }
        });
        btnArquivo.add(mnuBackup);

        jMenuBar1.add(btnArquivo);

        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/disquete_32x32.png"))); // NOI18N
        btnCadastro.setText("F3-Cadastro");

        mnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        btnCadastro.add(mnuClientes);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, 0));
        jMenuItem1.setText("Bairro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btnCadastro.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, 0));
        jMenuItem2.setText("Cidade");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        btnCadastro.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, 0));
        jMenuItem4.setText("Endereço");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        btnCadastro.add(jMenuItem4);

        mnuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, 0));
        mnuUsuario.setText("Usuário");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        btnCadastro.add(mnuUsuario);

        mnuPorcentagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, 0));
        mnuPorcentagem.setText("Porcentagem");
        mnuPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPorcentagemActionPerformed(evt);
            }
        });
        btnCadastro.add(mnuPorcentagem);

        jMenuBar1.add(btnCadastro);

        btnCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/moedas_32x32.png"))); // NOI18N
        btnCaixa.setText("F4-Conta Corrente");
        btnCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCaixaMouseClicked(evt);
            }
        });
        btnCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCaixaKeyPressed(evt);
            }
        });
        jMenuBar1.add(btnCaixa);

        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/relatorio_32x32.png"))); // NOI18N
        btnRelatorios.setText("F5-Relatórios");

        jMenu2.setText("Clientes - Todos");

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        jMenuItem13.setText("Por Código");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, 0));
        jMenuItem7.setText("Por Nome");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        btnRelatorios.add(jMenu2);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, 0));
        jMenuItem8.setText("Extrato Conta Corrente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        btnRelatorios.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, 0));
        jMenuItem9.setText("Analitico Conta Corrente");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        btnRelatorios.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, 0));
        jMenuItem10.setText("Saldo Clientes - Só devedores");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        btnRelatorios.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, 0));
        jMenuItem11.setText("Saldo Clientes - Só credores");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        btnRelatorios.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, 0));
        jMenuItem12.setText("Auditoria");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        btnRelatorios.add(jMenuItem12);

        jMenuBar1.add(btnRelatorios);

        mnuUtilitarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/calculadora_32x32.png"))); // NOI18N
        mnuUtilitarios.setText("F6-Utilitários");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Calculadora");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuUtilitarios.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Recados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuUtilitarios.add(jMenuItem6);

        jMenuBar1.add(mnuUtilitarios);

        btnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/info_32x32.png"))); // NOI18N
        btnSobre.setText("F7-Sobre");
        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSobre);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/casa_32x32.png"))); // NOI18N
        btnSair.setText("F8-Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static boolean cliente = false;
    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed

        cliente = true;
        new ClientesVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed
    public static boolean planoContas = false;    public static boolean bairro = false;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        bairro = true;
        new PesquisaVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public static boolean cidade = false;
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        cidade = true;
        new PesquisaVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    public static boolean endereco = false;
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        endereco = true;
        new PesquisaVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        if (UtilVIEW.PedeSenha("05644635660") == true) {
            new UsuarioVIEW(null, true).setVisible(true);
        } else if (UtilVIEW.PedeSenha("05644635660") == false) {

        }
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void btnCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaixaMouseClicked
//        UtilVIEW.jpf.requestFocusInWindow();
//        if (UtilVIEW.PedeSenha("1995") == true) {
//            new ContaCorrenteVIEW(null, true).setVisible(true);
//        } else if (UtilVIEW.PedeSenha("1995") == false) {
//            
//        }
        new PedeSenhaVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_btnCaixaMouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            Runtime.getRuntime().exec("StikyNot.exe");
        } catch (IOException ex) {
            System.out.println("Arquivo não encontrado " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            Runtime.getRuntime().exec("calc.exe");
        } catch (IOException ex) {
            System.out.println("Arquivo não encontrado " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseClicked
        new SobreVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_btnSobreMouseClicked
public static boolean relDevedores = false;
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       relDevedores = true;
       new ContaCorrenteVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed
public static boolean relCredores = false;
    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        relCredores = true;
        new ContaCorrenteVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed
public static boolean relExtrato = false;
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        relExtrato = true;        
        new ContaCorrenteVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed
    public static boolean relatorioAnalitico = false;
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        relatorioAnalitico = true;
        new ContaCorrenteVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed
    public static boolean auditoria = false;
    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        if (UtilVIEW.PedeSenha("05644635660") == true) {
            auditoria = true;
            new RelatorioPeriodoVIEW(null, true).setVisible(true);
        } else if (UtilVIEW.PedeSenha("05644635660") == false) {
            JOptionPane.showMessageDialog(null, "Senha não confere!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        int sair = -1;
        sair = JOptionPane.showConfirmDialog(null, "Deseja sair?", "PERGUNTA",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (sair == 0) {
            try {
                UtilVIEW.realizaBackup();
            } catch (IOException | InterruptedException ex) {
                System.out.println("" + ex.getMessage());
            }
            if (UtilVIEW.VerificaConexao() == true) {
                try {
                    UtilVIEW.EmailAnexo();
                } catch (MessagingException | UnsupportedEncodingException ex) {
                    System.out.println("" + ex.getMessage());
                }
            }
           System.exit(0);
        } else if (sair == 1) {

        }
    }//GEN-LAST:event_btnSairMouseClicked

    private void mnuBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBackupActionPerformed

        try {
            UtilVIEW.realizaBackup();
            JOptionPane.showMessageDialog(null, "Backup realizado com sucesso!", 
                    "MENSAGEM", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException | InterruptedException ex) {
            System.out.println("" + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Erro "+ex.getMessage());
        }
        if (UtilVIEW.VerificaConexao() == true) {
            try {
                UtilVIEW.EmailAnexo();
            } catch (MessagingException | UnsupportedEncodingException ex) {
                System.out.println("" + ex.getMessage());
                JOptionPane.showMessageDialog(null, "Não conectado! "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_mnuBackupActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        RelatorioClientes("CÓDIGO", 1);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        RelatorioClientes("NOME", 2);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void btnCaixaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCaixaKeyPressed
        try {
            if(evt.getKeyChar() == KeyEvent.VK_ENTER){
                new PedeSenhaVIEW(null, true).setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCaixaKeyPressed

    private void mnuPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPorcentagemActionPerformed
        new ConfiguracaoVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_mnuPorcentagemActionPerformed

    public void RelatorioClientes(String tituloRelatorio, Integer ordenar) {
        try {
            int op = -1;
            op = JOptionPane.showConfirmDialog(null, "Impressora esta ligada?", "PERGUNTA",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (op == 0) {
                // this.dispose();
                URL arquivo = getClass().getResource("/Relatorios/Clientes.jasper");

                //JOptionPane.showMessageDialog(this, arquivo.toString());
                if (arquivo == null) {
                    System.out.println("ARQUIVO INEXISTENTE");
                } else {

                    ConectaBanco.ConectaPostgres();
                    JasperPrint rel = null;
                    Map parametros = new HashMap();
                    parametros.put("ordem", tituloRelatorio);
                    parametros.put("ordenar", ordenar);
                    JasperReport jr;
                    try {
                        jr = (JasperReport) JRLoader.loadObject(arquivo);
                        rel = JasperFillManager.fillReport(jr, parametros, ConectaBanco.con);
                        JasperViewer.viewReport(rel, false);
                    } catch (JRException ex) {
                        System.out.println("" + ex.getMessage());
                    }

                }
            } else if (op == 1) {

            }
        } catch (HeadlessException e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnArquivo;
    private javax.swing.JMenu btnCadastro;
    private javax.swing.JMenu btnCaixa;
    private javax.swing.JMenu btnRelatorios;
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenu btnSobre;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mnuBackup;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuPorcentagem;
    private javax.swing.JMenuItem mnuUsuario;
    private javax.swing.JMenu mnuUtilitarios;
    // End of variables declaration//GEN-END:variables
}
